fixes from updating relx

diff --git a/ext/monit/autodeploy-ctl b/ext/monit/autodeploy-ctl
--- a/ext/monit/autodeploy-ctl
+++ b/ext/monit/autodeploy-ctl
@@ -20,6 +20,9 @@ export HOME="/home/$appname"
 # NB: autodeploy.sh sets RELX_OUTPUT_DIR to /home/autodeploy/autodeploy
 apprel="$HOME/$appname/${appname}_release"
 
+pidfile=/var/run/$appname.pid
+logfile=/var/log/$appname/$appname.log
+
 function now
 {
   date '+%Y-%m-%d %H:%M:%S'
@@ -27,17 +30,17 @@ function now
 
 function pwarn
 {
-  echo "$(now) [warning]: $@" 1>&2
+  echo "$(now) [warning]: $@" 1>&2 | tee -a "$logfile"
 }
 
 function perr
 {
-  echo "$(now) [error]: $@" 1>&2
+  echo "$(now) [error]: $@" 1>&2 | tee -a "$logfile"
 }
 
 function pinfo
 {
-  echo "$(now) [info]: $@"
+  echo "$(now) [info]: $@" | tee -a "$logfile"
 }
 
 function errexit
@@ -98,9 +101,6 @@ ensure_executables "$escript" "$appctl"
 
 cd $HOME || errexit "could not cd to $HOME"
 
-pidfile=/var/run/$appname.pid
-logfile=/var/log/$appname/$appname.log
-
 # NB: file in this form:
 # export SECRET_zendesk_sms='THESECRET'
 # export SECRET_other_app='THESECRET'
@@ -110,20 +110,20 @@ if [[ -s $secrets_file ]]
 then
     source $secrets_file
 else
-  echo "[info] no secrets file at $secrets_file" 1>&2
+  pinfo "no secrets file at $secrets_file" 1>&2
 fi
 
 case $1 in
   start)
-    echo "[info] starting $appname $(date)" > $logfile 2>&1
+    pinfo "starting $appname $(date)" > $logfile 2>&1
     su -c "$appctl start" $appuser >> $logfile 2>&1
-    app_pid=$("$escript" "$nodetool" -name $appname@127.0.0.1 -setcookie $appname rpcterms os getpid '' | sed -e's/"//g')
+    app_pid=$("$escript" "$nodetool" -name $appname@127.0.0.1 -setcookie $appname rpcterms os getpid | sed -e's/"//g')
     echo $app_pid > $pidfile
     exit 0
     ;;
 
   stop)
-    echo "[info] stopping $appname $(date)" >> $logfile 2>&1
+    pinfo "stopping $appname $(date)" >> $logfile 2>&1
     su -c "$appctl stop" $appuser >> $logfile 2>&1
     rm -f $pidfile
     exit 0
